//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication88.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dr
    {
        public int drid { get; set; }
        public string drname { get; set; }
    
        public virtual course course { get; set; }
    }
}
